apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: maas-api-dev

resources:
- ../../base/

secretGenerator:
- name: maas-api-admin-secret
  behavior: replace
  literals:
  - admin-api-key=letmein